camel:
  springboot:
    # The Camel context name
    name: Locations
  component:
    servlet:
      mapping:
        contextPath: /*

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
postgresql:
    service:
        database: sampledb
        name: postgresql
        password: password
        port: 5432
        username: dbuser
server:
    address: 0.0.0.0
spring:
    datasource:
        password: ${postgresql.service.password}
        url: jdbc:postgresql://${postgresql.service.name}:${postgresql.service.port}/${postgresql.service.database}
        username: ${postgresql.service.username}
    